[package]
name = "anvyx-backend"
version.workspace = true
edition.workspace = true

[dependencies]
anvyx-externs = { path = "../externs" }
anvyx-frontend = { path = "../frontend" }
anvyx-runtime = { path = "../runtime" }
fd-lock = "4.0"
sha2 = "0.10"

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
